window.GAME_DB = {
  game: { id: 'dream-town', title: '夢想小鎮' },
  categories: [
    {
      key: 'combos', slug: 'combos', label: 'Combo 組合', icon: '🔗',
      intro: '相鄰 combo 組合：三棟相容建築邊相接即觸發，對建築的基礎地價與商品價施加乘數加成（由 100% 起算）。以下收錄精選約 52 組較高加成組合（全遊戲共約 184 組）。衝全球挑戰血量看「地價」高者，衝利潤看「商品價」高者。建築名保留英文原名。',
      columns: ['Combo', '三棟建築', '地價', '商品價'],
      rows: [
        ['Castle', 'Palace＋Castle＋Kairo Statue', '250%', '40%'],
        ['Subway', 'Subway＋Office Tower＋High-Rise', '250%', '40%'],
        ['Animal Love', 'Safari Park＋Zoo＋Aquarium', '250%', '40%'],
        ['Cherry Special', '3-Star Hotel＋Gold Trophy＋Weeping Cherry', '250%', '40%'],
        ['Ackbar', 'Ackbar Statue＋Gold Trophy＋Kairo Bldg', '250%', '40%'],
        ['Kairodad', 'Kairodad Statue＋Gold Trophy＋TV Station', '250%', '40%'],
        ['Sheepy', 'Sheepy Statue＋Gold Trophy＋School', '250%', '40%'],
        ['Wariobot', 'Wariobot Statue＋Gold Trophy＋Ranch', '250%', '40%'],
        ['Chimpan Z', 'Chimpan Z Statue＋Gold Trophy＋Gym', '250%', '40%'],
        ['Critter', 'Aquarium＋Zoo＋Ranch', '190%', '65%'],
        ['Amusement', 'Comms Tower＋TV Station＋Concert Hall', '190%', '65%'],
        ['Consortium', 'Office Tower＋Weeping Cherry＋High-Rise', '190%', '65%'],
        ['Big Bucks', 'Kairo Statue＋Office Tower＋BBQ House', '190%', '65%'],
        ['Aviation', 'Rocket Hall＋Helipad＋Airport', '190%', '65%'],
        ['Sushi Special', 'Comms Tower＋Gold Trophy＋Sushi Joint', '190%', '65%'],
        ['Space', 'Planetarium＋Rocket Hall＋Octo-Alien Statue', '190%', '65%'],
        ['Smiley', 'Fountain Plaza＋Theme Park＋Sally Prin Statue', '190%', '65%'],
        ['Kairoman', 'Kairoman Statue＋Gold Trophy＋Cinema', '190%', '65%'],
        ['Bearington', 'Bearington Statue＋Gold Trophy＋Home Elec.', '190%', '65%'],
        ['Bunny', 'Bunny Statue＋Gold Trophy＋Baseball Park', '190%', '65%'],
        ['Eventful', 'Cinema＋Theme Park＋Concert Hall', '210%', '45%'],
        ['High-Rise', 'High-Rise＋Skyscraper＋Kairo Bldg', '210%', '45%'],
        ['Date', 'Theme Park＋Zoo＋Cinema', '210%', '45%'],
        ['Special', 'Airport＋TV Station＋Skyscraper', '210%', '45%'],
        ['Hollywood', 'Cinema＋Theme Park＋Jewelry Shop', '210%', '35%'],
        ['Sporty', 'Stadium＋Baseball Park＋Gym', '210%', '35%'],
        ['DIY', 'Dept. Store＋Furniture Shop＋Home Elec.', '210%', '35%'],
        ['Spring Deal', 'Boutique＋Cherry Tree＋Dept. Store', '210%', '35%'],
        ['Athletic', 'Sports Grounds＋Gym＋Stadium', '210%', '35%'],
        ['Furry Critter', 'Safari Park＋Kairopuppy Statue＋Pet Shop', '210%', '35%'],
        ['Grown-Up', 'Dance Club＋Casino＋Tapas Bar', '150%', '60%'],
        ['Kairo Park', 'Kairo Statue＋Game Shop＋Kairo Bldg', '150%', '60%'],
        ['Movie Special', 'Dept. Store＋Gold Trophy＋Cinema', '150%', '60%'],
        ['Healthcare', 'Local Center＋Hospital＋Subway', '150%', '60%'],
        ['Oriental', 'Pagoda＋Shrine＋Monument', '170%', '40%'],
        ['Celeb', 'Castle＋Boutique＋Dept. Store', '170%', '40%'],
        ['Business', 'High-Rise＋Skyscraper＋Bank', '170%', '40%'],
        ['Golf', 'Golf Training Center＋Golf Course＋Sports Shop', '170%', '40%'],
        ['Touristy', 'Spa Hotel＋Temple＋Gift Shop', '185%', '30%'],
        ['Estate', 'Contractors＋Estate Agent＋Furniture Shop', '185%', '30%'],
        ['Posh', 'Jewelry Shop＋3-Star Hotel＋Bank', '185%', '30%'],
        ['Pleasure', 'Game Arcade＋Bowling Alley＋Casino', '185%', '30%'],
        ['Vehicle', 'Bike Shop＋Motorcycle Shop＋Car Dealer', '125%', '55%'],
        ['Day Out', 'Museum＋Aquarium＋Cinema', '125%', '55%'],
        ['Culture', 'Jewelry Shop＋Museum＋Cinema', '125%', '55%'],
        ['Smart', 'Planetarium＋School＋Museum', '125%', '55%'],
        ['Fashion (#2)', 'Boutique＋Shoe Shop＋Beautician', '145%', '35%'],
        ['Medical', 'Hospital＋Drugstore＋24-7 Mart', '145%', '35%'],
        ['Rural', 'Farm＋Ranch＋Fishing Pond', '145%', '35%'],
        ['Popular', 'Home Center＋Estate Agent＋Supermarket', '145%', '35%'],
        ['Education', 'School＋Cram School＋Bookstore', '165%', '25%'],
        ['Intellect', 'Bookstore＋Museum＋School', '165%', '25%']
      ]
    },
    {
      key: 'buildings', slug: 'buildings', label: '建築索引', icon: '🏙️',
      intro: '出現在精選 combo 中的 84 種建築反查表：類型、出現在幾個 combo，以及所屬 combo 名稱。「出現數」越高代表越泛用、越值得優先擺放（例如 Gold Trophy 出現在 11 個 combo）。建築名保留英文原名。',
      columns: ['建築', '類型', '出現數', '所屬 Combo'],
      rows: [
        ['Gold Trophy', '地標', '11', 'Cherry Special・Ackbar・Kairodad・Sheepy・Wariobot・Chimpan Z・Sushi Special・Kairoman・Bearington・Bunny・Movie Special'],
        ['Cinema', '娛樂', '7', 'Kairoman・Eventful・Date・Hollywood・Movie Special・Day Out・Culture'],
        ['Dept. Store', '商店', '4', 'DIY・Spring Deal・Movie Special・Celeb'],
        ['High-Rise', '住宅大樓', '4', 'Subway・Consortium・High-Rise・Business'],
        ['Museum', '教育文化', '4', 'Day Out・Culture・Smart・Intellect'],
        ['School', '教育', '4', 'Sheepy・Smart・Education・Intellect'],
        ['Theme Park', '娛樂', '4', 'Smiley・Eventful・Date・Hollywood'],
        ['Aquarium', '動物自然', '3', 'Animal Love・Critter・Day Out'],
        ['Boutique', '商店', '3', 'Spring Deal・Celeb・Fashion (#2)'],
        ['Gym', '運動', '3', 'Chimpan Z・Sporty・Athletic'],
        ['Jewelry Shop', '商店', '3', 'Hollywood・Posh・Culture'],
        ['Kairo Bldg', '地標大樓', '3', 'Ackbar・High-Rise・Kairo Park'],
        ['Kairo Statue', '地標雕像', '3', 'Castle・Big Bucks・Kairo Park'],
        ['Office Tower', '商業大樓', '3', 'Subway・Consortium・Big Bucks'],
        ['Ranch', '農牧', '3', 'Wariobot・Critter・Rural'],
        ['Skyscraper', '大樓', '3', 'High-Rise・Special・Business'],
        ['TV Station', '媒體娛樂', '3', 'Kairodad・Amusement・Special'],
        ['Zoo', '動物自然', '3', 'Animal Love・Critter・Date'],
        ['3-Star Hotel', '觀光住宿', '2', 'Cherry Special・Posh'],
        ['Airport', '交通', '2', 'Aviation・Special'],
        ['Bank', '金融服務', '2', 'Business・Posh'],
        ['Baseball Park', '運動', '2', 'Bunny・Sporty'],
        ['Bookstore', '教育', '2', 'Education・Intellect'],
        ['Casino', '娛樂', '2', 'Grown-Up・Pleasure'],
        ['Castle', '地標', '2', 'Castle・Celeb'],
        ['Comms Tower', '媒體娛樂', '2', 'Amusement・Sushi Special'],
        ['Concert Hall', '娛樂', '2', 'Amusement・Eventful'],
        ['Estate Agent', '服務', '2', 'Estate・Popular'],
        ['Furniture Shop', '商店', '2', 'DIY・Estate'],
        ['Home Elec.', '商店', '2', 'Bearington・DIY'],
        ['Hospital', '醫療', '2', 'Healthcare・Medical'],
        ['Planetarium', '教育文化', '2', 'Space・Smart'],
        ['Rocket Hall', '觀光地標', '2', 'Aviation・Space'],
        ['Safari Park', '動物自然', '2', 'Animal Love・Furry Critter'],
        ['Stadium', '運動', '2', 'Sporty・Athletic'],
        ['Subway', '交通', '2', 'Subway・Healthcare'],
        ['Weeping Cherry', '景觀自然', '2', 'Cherry Special・Consortium'],
        ['24-7 Mart', '商店', '1', 'Medical'],
        ['Ackbar Statue', '地標雕像', '1', 'Ackbar'],
        ['BBQ House', '餐飲', '1', 'Big Bucks'],
        ['Bearington Statue', '地標雕像', '1', 'Bearington'],
        ['Beautician', '服務美容', '1', 'Fashion (#2)'],
        ['Bike Shop', '商店', '1', 'Vehicle'],
        ['Bowling Alley', '娛樂', '1', 'Pleasure'],
        ['Bunny Statue', '地標雕像', '1', 'Bunny'],
        ['Car Dealer', '商店', '1', 'Vehicle'],
        ['Cherry Tree', '景觀自然', '1', 'Spring Deal'],
        ['Chimpan Z Statue', '地標雕像', '1', 'Chimpan Z'],
        ['Contractors', '服務', '1', 'Estate'],
        ['Cram School', '教育', '1', 'Education'],
        ['Dance Club', '娛樂', '1', 'Grown-Up'],
        ['Drugstore', '醫療', '1', 'Medical'],
        ['Farm', '農牧', '1', 'Rural'],
        ['Fishing Pond', '農牧自然', '1', 'Rural'],
        ['Fountain Plaza', '景觀廣場', '1', 'Smiley'],
        ['Game Arcade', '娛樂', '1', 'Pleasure'],
        ['Game Shop', '商店', '1', 'Kairo Park'],
        ['Gift Shop', '商店', '1', 'Touristy'],
        ['Golf Course', '運動', '1', 'Golf'],
        ['Golf Training Center', '運動', '1', 'Golf'],
        ['Helipad', '交通', '1', 'Aviation'],
        ['Home Center', '商店', '1', 'Popular'],
        ['Kairodad Statue', '地標雕像', '1', 'Kairodad'],
        ['Kairoman Statue', '地標雕像', '1', 'Kairoman'],
        ['Kairopuppy Statue', '地標雕像', '1', 'Furry Critter'],
        ['Local Center', '服務', '1', 'Healthcare'],
        ['Monument', '地標', '1', 'Oriental'],
        ['Motorcycle Shop', '商店', '1', 'Vehicle'],
        ['Octo-Alien Statue', '地標雕像', '1', 'Space'],
        ['Pagoda', '文化地標', '1', 'Oriental'],
        ['Palace', '地標', '1', 'Castle'],
        ['Pet Shop', '商店', '1', 'Furry Critter'],
        ['Sally Prin Statue', '地標雕像', '1', 'Smiley'],
        ['Sheepy Statue', '地標雕像', '1', 'Sheepy'],
        ['Shoe Shop', '商店', '1', 'Fashion (#2)'],
        ['Shrine', '文化地標', '1', 'Oriental'],
        ['Spa Hotel', '觀光住宿', '1', 'Touristy'],
        ['Sports Grounds', '運動', '1', 'Athletic'],
        ['Sports Shop', '商店', '1', 'Golf'],
        ['Supermarket', '商店', '1', 'Popular'],
        ['Sushi Joint', '餐飲', '1', 'Sushi Special'],
        ['Tapas Bar', '餐飲', '1', 'Grown-Up'],
        ['Temple', '文化地標', '1', 'Touristy'],
        ['Wariobot Statue', '地標雕像', '1', 'Wariobot']
      ]
    },
    {
      key: 'facilities', slug: 'facilities', label: '設施角色', icon: '🏢',
      intro: '依功能整理夢想小鎮的設施角色。教育設施讓學生就近學習成年；住宅決定人口與後期旅遊券產能；支援建築產出旅遊券（Tour Voucher）；賣商品的建築需臨路才能營業。',
      columns: ['角色', '代表建築', '說明'],
      rows: [
        ['教育設施', 'School・Cram School・Bookstore・Museum・Bench・Doggie Statue', '新居民以「學生」身分入住，需就近使用教育設施學習才能成年並提升能力；學生移動範圍有限，務必蓋在住宅附近。'],
        ['住宅', 'House（各等級）', '決定城鎮人口；後期靠 Level 5–6 高級住宅衝旅遊券產量。'],
        ['產券支援建築', 'Bench・Toilet・Statue・Phone Booth・Info Center', '產出旅遊券（Tour Voucher）；Rank 60+ 後隔區約 30 棟 Lv5–6 住宅＋10 棟支援建築可高效刷券。'],
        ['商店與設施', 'Store・Shop・Restaurant 等', '賺取金幣；賣商品的建築需臨路（road access）才能營業，並靠 combo 拉高地價與商品價。'],
        ['交通建築', 'Airport・Helipad・Subway', 'Airport 提供最佳載具（+16 移動範圍）且免探索要求，值得優先蓋。'],
        ['地標與雕像', 'Kairo Statue・Gold Trophy・各角色 Statue', '基礎地價／商品價高的 S 級建築，塞進多重 combo 交疊區效益最大。']
      ]
    }
  ]
};
